### ISSUE TITLE
resp.StatusCode can't be <=200 *and* >= 299

### ISSUE THREAD

**Issue by superawesome** [mapr/KubernetesDataFabric#1]
This "if" block never matches:

https://github.com/mapr/KubernetesDataFabric/blob/ae2396744889a617205574f9ae57e6944a431a85/build/provisioner/maprfs-provisioner/main.go#L334

**Comment by sarjeet2013** [comment]
The following commit fixed the issue: https://github.com/mapr/KubernetesDataFabric/commit/cd13c97dc1b100e7d442d47b2a521280b786233a
